name: 'Run PyTest'
description: 'Run PyTest for the Integration tests'
inputs:
  tests:
    description: 'The tests to run'
    required: true
  timeout:
    description: 'Test timeout'
    required: true
  cov_name:
    description: 'Name of coverage file'
    required: false
    default: ''
  n_threads:
    description: 'The number of threads to run with'
    required: false
    default: 'auto'
runs:
  using: "composite"
  steps:
    - id: test_dependencies
      run: |
        if [[ -z "${PYTEST_DEPENDENCIES_INSTALLED}" ]]
        then
            # coverage version capped due to https://github.com/nedbat/coveragepy/issues/883
            pip install python-coveralls "coverage>=5.0.0" pytest-cov pytest-timeout pytest-forked pytest-progress pytest-instafail "pytest-xdist==1.34.0"
            echo PYTEST_DEPENDENCIES_INSTALLED=true >> $GITHUB_ENV
        fi
      shell: bash
      
    - id: set_env
      env:
        COV_OPTS: --cov-config=.coveragerc --cov-branch
          --cov spynnaker8 --cov spynnaker --cov spinn_front_end_common --cov pacman
          --cov data_specification --cov spinnman --cov spinn_machine --cov spalloc
          --cov spinn_utilities --cov spinnaker_graph_front_end
          --cov-report xml:coverage.xml --cov-append
      run: |
        if [[ ! -z "${{ inputs.cov_name }}" ]] 
        then
          mkdir -p junit/
          echo "<testsuite tests='0'></testsuite>" > junit/${{ inputs.cov_name }}.xml
          echo "COV_ARGS=${COV_OPTS} --junitxml junit/${{ inputs.cov_name }}.xml" >> $GITHUB_ENV
        fi
      shell: bash
      
    - id: pytest_run
      run: |
        py.test ${{ inputs.tests }} -rs -n ${{ inputs.n_threads }} --forked --show-progress \
          ${COV_ARGS} --timeout ${{ inputs.timeout }} --log-level=INFO
      shell: bash
