name: "Clone matching"
description: "Clone the branch with a name matching that of the tests being done, or master if that doesn't exist"
inputs:
  repository:
    description: The repository (or repositories on multiple lines) to clone
    required: true
runs:
  using: "composite"
  steps:
    - id: git_clone_matching
      run: |
        SAVEIFS=$IFS   # Save current IFS
        IFS=$'\n'      # Change IFS to new line
        REPOS=(${{ inputs.repository }}) # split to array
        IFS=$SAVEIFS   # Restore IFS
        for (( i=0; i<${#REPOS[@]}; i++))
        do
          REPO=${REPOS[$i]}
          echo "Trying branch $GITHUB_REF_NAME of $REPO"
          if git clone --branch $GITHUB_REF_NAME --depth 1 $REPO
          then
          else
            echo "Check out HEAD of $REPO"
            git clone --depth 1 $REPO
          fi
        done
      shell: bash
